DROP TABLE Seller CASCADE CONSTRAINTS;
DROP TABLE Buyer CASCADE CONSTRAINTS;
DROP TABLE City CASCADE CONSTRAINTS;
DROP TABLE Agent_Person CASCADE CONSTRAINTS;
DROP TABLE Apartment CASCADE CONSTRAINTS;
DROP TABLE Apartment_Sale CASCADE CONSTRAINTS;
DROP TABLE Visit CASCADE CONSTRAINTS;
